CREATE TABLE emp 
   (	"EMP_NUM" NUMBER NOT NULL ENABLE, 
	"COMSIZE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"COMPEOPLE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"FIELD" VARCHAR2(100 BYTE) NOT NULL ENABLE,
	"ROLE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CAREER" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"SALARY_STATUS" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"SALARY" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PERIODTIME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"EDUCATION" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"MAJOR" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"CERTIFICATION" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"LOCATION" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"WORKSTART" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"MEM_NUM" NUMBER NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"ADVICE" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"LOCATION_API" VARCHAR2(300 BYTE), 
	"REGISTER_DATE" DATE NOT NULL ENABLE, 
	"M_DATE" DATE, 
	"EMP_STATUS" NUMBER NOT NULL ENABLE, 
	"LOCATION_API_LAT" VARCHAR2(20 BYTE), 
	"LOCATION_API_LNG" VARCHAR2(20 BYTE),
    constraint emp_pk primary key (emp_num),
	constraint emp_fk foreign key (mem_num) references hwmember(mem_num)
   );

create sequence emp_seq;