spring:
  profiles:
    active: local #local,dev,real
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: seohyeonjin787@gmail.com
    password: qwhh wgbt topw igxu
    properties:
      smtp.auth : true
      mail:
        smtp:
          starttls:
            enable: true
            required : true
    test-connection: true
  data:
    redis:
      host: localhost
      port: 6379
    
  mvc:
    view: #view 경로 및 확장자 지정
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: c##toy1
    password: 1234
    hikari: #커넥션풀  
      connection-timeout: 30000 #클라이언트가 pool에 connection을 요청하는데 기다리는 최대시간을 설정 30초
      maximum-pool-size: 10 #최대 커넥션 개수
      max-lifetime: 1800000 #커넥션 풀에서 살아있을수 있는 커넥션의 최대 수명 시간 1,800초 (30분)
  
  messages: #메시지
    basename: varidation.properties
    encoding: UTF-8
  
  devtools: #view reload
    livereload:
      enabled: true
    
    restart: #컨트롤러, 모델단이 바뀌었을때 프로젝트 재 시작 설정
      enabled: true
      
  servlet:
    multipart:
      max-file-size: 50MB #파일 한개당 최대 사이즈
      max-request-size: 200MB #요청당 최대 파일 크기
        
mybatis: #mybatis 설정
  type-aliases-package: kr.spring.**.vo
  mapper-locations: kr/spring/**/dao/*.xml
  
logging: #로그지정
  level:
    '[kr.spring]': debug
    
server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true #http 인코딩 지원을 활성화할지 여부
      force: true

  tomcat:
    max-http-form-post-size: 200MB #톰캣이 허용하는 파일 업로드 사이즈